# Basic
title: Leo's Home
subtitle: 每天尝试一点新鲜玩意
welcome_message: 目前就职于杭州思达电子科技发展有限公司<br />任职软件工程师
description: 嗨, 我是雷梓健(@LibertyLeo)<br />一名90后iOS开发者
language: zh-hans
creator: <a href="https://LibertyLeo.github.io">@LibertyLeo</a>

url: "https://LibertyLeo.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 进入博客

# Navigation buttons in the front page.
nav:
    # - {title: 项目, description: 项目列表, url: 'http://project.onevcat.com'}
    # - {title: 关于, description: 关于我的一点点介绍, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: LibertyLeo
    # duoshuo: 
    
# Social
social:
    weibo: zijianlei
    github: LibertyLeo
    mail: leoizy@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
